name = "LKH"
uuid = "294deba0-74fa-42c9-af84-c3834b01fefc"
authors = ["Changhyun Kwon <chkwon@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
